import { useState } from 'react'
import * as Checkbox from '@radix-ui/react-checkbox'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Check, Download, FolderOpen, RotateCcw, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { createJob, getQueue, transitionVideos } from './api'

export function QueuePage({ startJob }) {
  const queryClient = useQueryClient(); const [selected, setSelected] = useState(new Set())
  const { data = { items: [], ready: 0, waiting_capacity: 0 }, isPending, error } = useQuery({ queryKey: ['queue'], queryFn: getQueue, refetchInterval: 5000 })
  const rows = data.items || []; const ready = rows.filter(row => row.queue_state === 'ready')
  const remove = useMutation({ mutationFn: items => transitionVideos({ items: items.map(row => ({ source_id: row.source_id, video_id: row.video_id })), status: 'discovered', expected_status: 'queued' }), onSuccess: () => { setSelected(new Set()); queryClient.invalidateQueries({ queryKey: ['queue'] }); queryClient.invalidateQueries({ queryKey: ['videos'] }); queryClient.invalidateQueries({ queryKey: ['overview'] }); toast.success('Đã đưa video về Review') }, onError: err => toast.error(err.message) })
  const startDownload = async () => { const chosen = ready.filter(row => !selected.size || selected.has(`${row.source_id}:${row.video_id}`)); const sourceIds = [...new Set(chosen.map(row => row.source_id))]; if (!sourceIds.length) return toast.error('Không có video Ready để tải'); try { const job = await createJob({ kind: 'download', source_ids: sourceIds }); startJob(job.id); toast.success('Download job đã bắt đầu') } catch (err) { toast.error(err.message) } }
  const selectedRows = rows.filter(row => selected.has(`${row.source_id}:${row.video_id}`))
  return <section className="page"><header className="page-header"><div><p className="eyebrow">3 / DOWNLOAD QUEUE</p><h1>Download queue</h1><p>{data.ready} ready · {data.waiting_capacity} waiting for capacity</p></div><button className="button button-primary" onClick={startDownload}><Download size={17} /> Start download</button></header>{selected.size > 0 && <div className="selection-bar"><strong>{selected.size} selected</strong><button className="bulk-action" onClick={() => remove.mutate(selectedRows)}><Trash2 size={15} /> Return to review</button><button onClick={() => setSelected(new Set())}>Clear</button></div>}<div className="table-card"><table><thead><tr><th><Checkbox.Root className="checkbox" checked={rows.length > 0 && selected.size === rows.length} onCheckedChange={checked => setSelected(checked ? new Set(rows.map(row => `${row.source_id}:${row.video_id}`)) : new Set())}><Checkbox.Indicator><Check size={13} /></Checkbox.Indicator></Checkbox.Root></th><th>Video</th><th>Source</th><th>Destination</th><th>Capacity</th><th>Status</th></tr></thead><tbody>{isPending && <tr><td colSpan="6"><div className="table-state">Loading queue…</div></td></tr>}{error && <tr><td colSpan="6"><div className="table-state error">{error.message}</div></td></tr>}{rows.map(row => { const key = `${row.source_id}:${row.video_id}`; return <tr key={key}><td><Checkbox.Root className="checkbox" checked={selected.has(key)} onCheckedChange={() => setSelected(current => { const next = new Set(current); next.has(key) ? next.delete(key) : next.add(key); return next })}><Checkbox.Indicator><Check size={13} /></Checkbox.Indicator></Checkbox.Root></td><td><strong>{row.title || row.video_id}</strong><small>{row.video_id}</small></td><td>{row.source_label}</td><td><button className="path-button" onClick={() => window.desktop?.openPath(row.path_download)}><FolderOpen size={14} /> Open folder</button></td><td>{row.capacity} slots</td><td><span className={`status status-${row.queue_state === 'ready' ? 'fresh' : 'review'}`}><span />{row.queue_state === 'ready' ? 'Ready' : 'Waiting for capacity'}</span></td></tr>})}{!isPending && rows.length === 0 && <tr><td colSpan="6"><div className="table-state"><RotateCcw size={18} /> Queue is empty. Approve videos from Review.</div></td></tr>}</tbody></table></div></section>
}
