import { useDeferredValue, useEffect, useMemo, useRef, useState } from 'react'
import * as Checkbox from '@radix-ui/react-checkbox'
import * as Dialog from '@radix-ui/react-dialog'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Check, Clock3, EyeOff, ExternalLink, Search, SlidersHorizontal, Undo2, X } from 'lucide-react'
import { toast } from 'sonner'
import { getSources, getVideos, transitionVideos } from './api'
import { SelectField } from './SelectField'

const HOLD_REASONS = ['Copyright risk', 'Quality uncertain', 'Duplicate / similar', 'Needs discussion', 'Other']
const compact = value => value == null ? '—' : new Intl.NumberFormat().format(value)
const select = (value, label) => ({ value, label })
const formatPublishedDate = value => {
  if (!value) return 'Pending'
  const raw = String(value).trim()
  const compactDate = raw.match(/^(\d{4})(\d{2})(\d{2})$/)
  const isoDate = raw.match(/^(\d{4})-(\d{2})-(\d{2})/)
  const parts = compactDate || isoDate
  if (parts) return `${parts[3]}/${parts[2]}/${parts[1]}`
  const parsed = new Date(raw)
  return Number.isNaN(parsed.getTime())
    ? raw
    : new Intl.DateTimeFormat('vi-VN', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(parsed)
}

function HoldDialog({ open, onOpenChange, onConfirm, count }) {
  const [reason, setReason] = useState(HOLD_REASONS[0]); const [note, setNote] = useState(''); const [reviewAt, setReviewAt] = useState('')
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="dialog-content"><div className="dialog-heading"><div><p className="eyebrow">QUALITY GATE</p><Dialog.Title>Put {count} video{count === 1 ? '' : 's'} on Hold</Dialog.Title><Dialog.Description>Keep uncertain videos out of Queue without discarding them.</Dialog.Description></div><Dialog.Close className="icon-button" aria-label="Close"><X size={18} /></Dialog.Close></div><div className="source-form"><label>Reason<SelectField value={reason} onValueChange={setReason} options={HOLD_REASONS.map(item => select(item, item))} /></label><label>Note <span>Optional</span><textarea value={note} onChange={event => setNote(event.target.value)} placeholder="What should be checked before approval?" /></label><label>Review again on <span>Optional</span><input type="date" value={reviewAt} onChange={event => setReviewAt(event.target.value)} /></label><div className="dialog-actions"><Dialog.Close className="button button-ghost">Cancel</Dialog.Close><button className="button button-primary" onClick={() => onConfirm({ reason, note, reviewAt })}>Put on Hold</button></div></div></Dialog.Content></Dialog.Portal></Dialog.Root>
}

export function ReviewPage() {
  const queryClient = useQueryClient()
  const [filters, setFilters] = useState({ status: 'discovered', sourceId: '', keyword: '', excludeKeyword: '', contentType: '', metadataStatus: '', minViews: '', minDuration: '', maxDuration: '', publishedAfter: '', publishedBefore: '', sort: 'newest' })
  const [advanced, setAdvanced] = useState(false); const [holdOpen, setHoldOpen] = useState(false); const [selected, setSelected] = useState(new Set()); const selectionAnchorRef = useRef(null); const selectionModifierRef = useRef({ shiftKey: false })
  const deferredKeyword = useDeferredValue(filters.keyword); const { data: sources = [] } = useQuery({ queryKey: ['sources'], queryFn: () => getSources(false) })
  const queryFilters = { ...filters, keyword: deferredKeyword }; const { data, isPending, error } = useQuery({ queryKey: ['videos', queryFilters], queryFn: () => getVideos(queryFilters), refetchInterval: 5000 }); const rows = data?.items || []
  useEffect(() => { selectionAnchorRef.current = null; setSelected(new Set()) }, [JSON.stringify(queryFilters)])
  const chosen = useMemo(() => rows.filter(row => selected.has(`${row.source_id}:${row.video_id}`)), [rows, selected])
  const mutation = useMutation({ mutationFn: ({ target, items, reason = '', note = '', reviewAt = '' }) => transitionVideos({ items: items.map(row => ({ source_id: row.source_id, video_id: row.video_id })), status: target, expected_status: filters.status, reason, note, review_at: reviewAt }), onSuccess: (_, variables) => { queryClient.invalidateQueries(); setSelected(new Set()); toast.success(variables.target === 'queued' ? 'Approved — added to Queue' : variables.target === 'hold' ? 'Videos put on Hold' : 'Videos updated') }, onError: error => toast.error(error.message) })
  const rowKeys = useMemo(() => rows.map(row => `${row.source_id}:${row.video_id}`), [rows]); const update = patch => setFilters(current => ({ ...current, ...patch })); const recordSelectionModifier = event => { selectionModifierRef.current = { shiftKey: Boolean(event.shiftKey) } }; const toggle = key => { const anchorIndex = selectionModifierRef.current.shiftKey && selectionAnchorRef.current ? rowKeys.indexOf(selectionAnchorRef.current) : -1; const targetIndex = rowKeys.indexOf(key); selectionAnchorRef.current = key; setSelected(current => { const next = new Set(current); if (anchorIndex >= 0 && targetIndex >= 0) { const [from, to] = [anchorIndex, targetIndex].sort((a, b) => a - b); rowKeys.slice(from, to + 1).forEach(rowKey => next.add(rowKey)) } else if (next.has(key)) next.delete(key); else next.add(key); return next }) }; const clearSelection = () => { selectionAnchorRef.current = null; setSelected(new Set()) }; const allSelected = rowKeys.length > 0 && rowKeys.every(key => selected.has(key))
  const transition = target => mutation.mutate({ target, items: [...chosen] }); const hold = values => { setHoldOpen(false); mutation.mutate({ target: 'hold', items: [...chosen], ...values }) }
  return <section className="page review-page"><header className="page-header"><div><p className="eyebrow">2 / QUALITY REVIEW</p><h1>Review inbox</h1><p><p className="review-stat">{compact(rows.length)} videos ready · {selected.size} selected</p></p></div></header>
    <div className="toolbar review-filters"><label className="search"><Search size={17} /><input value={filters.keyword} onChange={event => update({ keyword: event.target.value })} placeholder="Include title keywords" /></label><SelectField value={filters.sourceId} onValueChange={sourceId => update({ sourceId })} ariaLabel="Source" options={[select('', 'All sources'), ...sources.map(source => select(source.id, source.label))]} /><SelectField value={filters.status} onValueChange={status => update({ status })} ariaLabel="Review status" options={[select('discovered', 'Needs review'), select('hold', 'Hold'), select('ignored', 'Ignored')]} /><SelectField value={filters.sort} onValueChange={sort => update({ sort })} ariaLabel="Sort videos" options={[select('newest', 'Newest'), select('trending', 'Views / day'), select('views', 'Most viewed'), select('duration_asc', 'Shortest'), select('duration_desc', 'Longest')]} /><button className={`row-action ${advanced ? 'active' : ''}`} onClick={() => setAdvanced(value => !value)}><SlidersHorizontal size={15} /> Filters</button></div>
    {advanced && <div className="quality-filters"><label>Exclude keywords<input value={filters.excludeKeyword} onChange={event => update({ excludeKeyword: event.target.value })} /></label><label>Type<SelectField value={filters.contentType} onValueChange={contentType => update({ contentType })} options={[select('', 'Any'), select('videos', 'Videos'), select('shorts', 'Shorts')]} /></label><label>Metadata<SelectField value={filters.metadataStatus} onValueChange={metadataStatus => update({ metadataStatus })} options={[select('', 'Any'), select('ready', 'Ready'), select('pending', 'Enriching'), select('missing', 'Missing')]} /></label><label>Min views<input type="number" min="0" value={filters.minViews} onChange={event => update({ minViews: event.target.value })} /></label><label>Min seconds<input type="number" min="0" value={filters.minDuration} onChange={event => update({ minDuration: event.target.value })} /></label><label>Max seconds<input type="number" min="0" value={filters.maxDuration} onChange={event => update({ maxDuration: event.target.value })} /></label><label>Published after<input type="date" value={filters.publishedAfter} onChange={event => update({ publishedAfter: event.target.value })} /></label><label>Published before<input type="date" value={filters.publishedBefore} onChange={event => update({ publishedBefore: event.target.value })} /></label><button className="row-action" onClick={() => update({ excludeKeyword: '', contentType: '', metadataStatus: '', minViews: '', minDuration: '', maxDuration: '', publishedAfter: '', publishedBefore: '' })}>Clear filters</button></div>}
    {selected.size > 0 && <div className="selection-bar sticky-actions"><strong>{selected.size} selected</strong><span>Shift-click range</span>{filters.status !== 'ignored' && <button className="bulk-action primary" onClick={() => transition('queued')}><Check size={15} /> Approve to Queue</button>}{filters.status !== 'hold' && <button className="bulk-action" onClick={() => setHoldOpen(true)}><Clock3 size={15} /> Hold</button>}{filters.status !== 'ignored' && <button className="bulk-action" onClick={() => transition('ignored')}><EyeOff size={15} /> Ignore</button>}{filters.status !== 'discovered' && <button className="bulk-action" onClick={() => transition('discovered')}><Undo2 size={15} /> Restore</button>}<button onClick={clearSelection}>Clear</button></div>}
    <div className="table-card review-table"><table><thead><tr><th><Checkbox.Root className="checkbox" checked={allSelected} onCheckedChange={checked => { selectionAnchorRef.current = null; setSelected(checked ? new Set(rowKeys) : new Set()) }}><Checkbox.Indicator><Check size={13} /></Checkbox.Indicator></Checkbox.Root></th><th>Preview</th><th>Video</th><th>Quality</th><th>Source</th><th>Published</th><th>Status</th></tr></thead><tbody>{isPending && <tr><td colSpan="7"><div className="table-state">Loading quality inbox…</div></td></tr>}{error && <tr><td colSpan="7"><div className="table-state error">{error.message}</div></td></tr>}{!isPending && rows.map(row => { const key = `${row.source_id}:${row.video_id}`; const state = row.metadata_status || 'pending'; return <tr key={key}><td><Checkbox.Root className="checkbox" checked={selected.has(key)} onPointerDown={recordSelectionModifier} onClick={recordSelectionModifier} onKeyDown={recordSelectionModifier} onCheckedChange={() => toggle(key)}><Checkbox.Indicator><Check size={13} /></Checkbox.Indicator></Checkbox.Root></td><td>{row.thumbnail ? <img className="thumbnail" src={row.thumbnail} alt="" loading="lazy" /> : <span className="thumbnail placeholder" />}</td><td><a className="video-title" href={row.source_url} target="_blank" rel="noreferrer">{row.title || row.video_id}<ExternalLink size={13} /></a><small>{row.video_id}</small>{filters.status === 'hold' && <small>{row.hold_reason}{row.review_at ? ` · revisit ${row.review_at}` : ' · no reminder'}</small>}</td><td><strong>{compact(row.view_count)} views</strong><small>{row.like_count == null ? 'Likes pending' : `${compact(row.like_count)} likes`} · {row.duration ? `${Math.round(row.duration)}s` : 'duration pending'}</small></td><td>{row.source_label}</td><td><time className="published-date" dateTime={row.upload_date || undefined}>{formatPublishedDate(row.upload_date)}</time></td><td><span className={`status status-${state === 'ready' ? 'fresh' : state === 'missing' ? 'review' : 'sync'}`}><span />{state}</span></td></tr>})}{!isPending && rows.length === 0 && <tr><td colSpan="7"><div className="table-state">No videos match these quality filters.</div></td></tr>}</tbody></table></div><HoldDialog open={holdOpen} onOpenChange={setHoldOpen} onConfirm={hold} count={chosen.length} /></section>
}
